import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-[100vh]">
        <div className="w-full bg-sky-700 h-15 p-2 flex items-center gap-5">
          <Link className='p-2 rounded hover:bg-sky-800' href='/'>Home</Link>
          <Link className='p-2 rounded hover:bg-sky-800' href='/dashboard'>Dashboard</Link>
          <Link className='p-2 rounded hover:bg-sky-800' href='/product'>Product</Link>
          <Link className='p-2 rounded hover:bg-sky-800' href='/user'>User</Link>
          <Link className='p-2 rounded hover:bg-sky-800' href='/new-product'>[NEW] Product</Link>
        </div>
        <div className="p-5 max-w-[100vw] min-h-full">
          {children}
        </div>
      </body>
    </html>
  );
}
